### ISSUE TITLE
Hyperlinks in text return to start of current chapter

### ISSUE THREAD

**Issue by dreg-mogul** [hyphen-reader/hyphen#45] opened 2016-03-13 22:38 UTC
Hi,

I'm currently reading a book that has hyperlinks that link to footnotes at the end of the chapter (please see attached). When clicking the link at the end of the chapter, I should be returned to my previous position. However, the link seems to return me to the beginning of the chapter. I have tested the same ePub in iBooks - the issue is not replicated, so I'm assuming that the problem is with Hyphen, rather than a formatting issue in the ePub. 

Please let me know if you need any further info. 

Thanks,

Anthony. 

![image](https://cloud.githubusercontent.com/assets/17817043/13731878/54048d46-e96c-11e5-8158-a7031e0a6648.jpeg)
![image](https://cloud.githubusercontent.com/assets/17817043/13731879/54233a16-e96c-11e5-9262-a4bddec224b5.jpeg)

**Comment by matt-curtis** [comment] 2016-03-13 23:59
Hello Anthony,

Could you send a copy of this ePub to hyphenreader@gmail.com?

**Comment by matt-curtis** [comment] 2016-03-14 14:41
Hello Anthony - I've checked and it appears this has been fixed in 2.0, as I can't reproduce the issue. I'll leave this issue open though until 2.0 releases.

**Closed as completed** 2016-09-11 09:33 UTC
Labels: bug, resolved in future release
